# HLint configuration file

- arguments: [-XTypeApplications]

- functions:
  - {name: unsafePerformIO, within: [Oscoin.Test.Crypto.Blockchain.Block.Helpers]}

- warn: {lhs: fmap, rhs: map}
- warn: {lhs: foldl, rhs: foldl'}
- warn: {lhs: return, rhs: pure}
- warn: {lhs: liftM, rhs: map}
- warn: {lhs: ap, rhs: (<*>)}
- warn: {lhs: mapM, rhs: traverse}
- warn: {lhs: concat (map f x), rhs: foldMap f x}
- warn: {lhs: second (const ()), rhs: void}
- warn: {lhs: map (const ()), rhs: void}

- ignore: {name: Use map, within: [Crypto.Data.Auth.Tree.Proof]}
- ignore: {name: Use map, within: [Data.Sequence.Circular]}
- ignore: {name: Collapse lambdas}

- ignore: {name: Reduce duplication}
- ignore: {name: Use concatMap}
- ignore: {name: Use ++}
- ignore: {name: Use &&}
- ignore: {name: Eta reduce}
- ignore: {name: Use lambda-case}
- ignore: {name: Use let}
- ignore: {name: Use newtype instead of data}
- ignore: {name: Redundant $}
- ignore: {name: Avoid reverse}
- ignore: {name: Use print}
- ignore: {name: Use camelCase}

- ignore:
    name: Avoid restricted function
    within:
    - Test.Oscoin.Protocol.Sync
