- package:
  - name: oscoin
  - section:
    - name: test:test
    - message:
      - name: Weeds exported
      - module:
        - name: Oscoin.Test.Consensus.Network
        - identifier:
          # BEGIN false positives
          - testableRun
          - testableScore
          - testableTick
          # END false positives

      - module:
        - name: Oscoin.Test.P2P.Gossip.Broadcast
        - identifier:
          # BEGIN debug functions
          - bootTopo
          - eagerTopo
          - lazyTopo
          - renderTopo
          # END debug functions

