- package:
  - name: oscoin
  - section:
    - name: test:test
    - message:
      - name: Weeds exported
- package:
  - name: oscoin
  - section:
    - name: test:documentation
    - message:
      - name: Redundant build-depends entry
      - depends: markdown-unlit
