- package:
  - name: oscoin
  - section:
    - name: test:test
    - message:
      - name: Weeds exported
      - module:
        - name: Oscoin.Test.Consensus.Network
        - identifier:
          # BEGIN false positives
          - testableRun
          - testableScore
          - testableTick
          # END false positives
      - module:
        - name: Oscoin.Test.P2P.IO
        - identifier:
          # BEGIN debug functions
          - props
          # END debug functions
      - module:
        - name: Oscoin.Test.P2P.Handshake
        - identifier:
          # BEGIN debug functions
          - props
          # END debug functions
      - module:
        - name: Oscoin.Test.P2P.Helpers
        - identifier:
          # BEGIN debug functions
          - accept
          - connect
          # END debug functions
      - module:
        - name: Oscoin.Test.P2P.Transport
        - identifier:
          # BEGIN debug functions
          - props
          # END debug functions
      - module:
        - name: Network.Gossip.Test.Broadcast
        - identifier:
          # BEGIN debug functions
          - props
          - bootTopo
          - eagerTopo
          - lazyTopo
          - renderTopo
          # END debug functions
      - module:
        - name: Network.Gossip.Test.Membership
        - identifier:
          # BEGIN debug functions
          - props
          # END debug functions
- package:
  - name: oscoin
  - section:
    - name: test:documentation
    - message:
      - name: Redundant build-depends entry
      - depends: markdown-unlit
