timeout: 7200s # Cache misses are slow to rebuild
options:
  machineType: N1_HIGHCPU_8
steps:
  - id: "Format (shell scripts)"
    waitFor: ["-"]
    name: gcr.io/cloud-builders/curl
    entrypoint: "bash"
    args: ["./scripts/check-shell-format.sh"]

  - id: "Lint (shellcheck)"
    waitFor: ["-"]
    name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args: ["./scripts/shellcheck.sh"]

  - id: "Build haskell-scratch rootfs"
    waitFor: ["-"]
    name: "eu.gcr.io/opensourcecoin/docker-haskell:8.6.4"
    args:
    - make
    - "-C"
    - /workspace/scripts/docker/haskell-scratch
    - "integer-gmp"

  - id: "Build haskell-scratch image"
    waitFor:
    - "Build haskell-scratch rootfs"
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
    - '-c'
    - |
      set -euox pipefail

      tar -cC /workspace/scripts/docker/haskell-scratch/root . | \
        docker import - eu.gcr.io/$PROJECT_ID/haskell-scratch:integer-gmp

  - id: "Load cache"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: "bash"
    env:
    - BRANCH_NAME=$BRANCH_NAME
    args:
    - "-c"
    - |
      source scripts/ci-cache.sh
      load-cache

  - id: "Build deps"
    name: "eu.gcr.io/opensourcecoin/docker-haskell:8.6.4"
    env:
    - STACK_ROOT=/workspace/.stack
    entrypoint: "bash"
    args:
    - "-c"
    - |
      set -euxo pipefail

      rm -rfv /workspace/.stack/global-project

      stack config set system-ghc  --global true
      stack config set install-ghc --global false

      stack build --no-terminal stylish-haskell hlint weeder
      stack build --no-terminal --test --dependencies-only

  - id: "Save cache"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: "bash"
    env:
    - BRANCH_NAME=$BRANCH_NAME
    args:
    - "-c"
    - |
      source scripts/ci-cache.sh
      save-cache

  - id: "Format (haskell)"
    waitFor:
    - Save cache
    name: "eu.gcr.io/opensourcecoin/docker-haskell:8.6.4"
    env:
    - STACK_ROOT=/workspace/.stack
    args:
    - ./scripts/check-haskell-format.sh

  - id: "Lint (hlint)"
    waitFor:
    - Save cache
    name: "eu.gcr.io/opensourcecoin/docker-haskell:8.6.4"
    env:
    - STACK_ROOT=/workspace/.stack
    args: ["stack", "exec", "--", "hlint", "."]

  - id: "Test & Build"
    waitFor:
    - Save cache
    name: "eu.gcr.io/opensourcecoin/docker-haskell:8.6.4"
    entrypoint: "bash"
    env:
    - STACK_ROOT=/workspace/.stack
    - BRANCH_NAME=$BRANCH_NAME
    args:
    - "-c"
    - |
      set -euo pipefail

      stack build \
        --test \
        --flag=oscoin:static \
        --no-terminal \
        --pedantic \
        --copy-bins \
        --local-bin-path=/workspace/bin \
        --haddock \
        --no-haddock-deps \
        --exec="mv $(stack path --local-doc-root) api-docs"

  - id: "Lint (weeder)"
    waitFor:
    - Test & Build
    name: "eu.gcr.io/opensourcecoin/docker-haskell:8.6.4"
    env:
    - STACK_ROOT=/workspace/.stack # weeder uses stack under the hood
    args: ["stack", "exec", "--", "weeder", "."]

  - id: "Build images"
    waitFor:
    - Lint (weeder)
    name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    env:
    - PROJECT_ID=$PROJECT_ID
    - COMMIT_SHA=$COMMIT_SHA
    - BRANCH_NAME=$BRANCH_NAME
    args:
    - "-c"
    - |
      set -euo pipefail

      bins=(
        /workspace/bin/oscoin
        /workspace/bin/oscoin-cli
      )

      echo "$${bins[*]}" | xargs -P8 -n1 ./scripts/docker/build-image.sh

  - id: "Publish Haddocks"
    waitFor:
    - Lint (weeder)
    name: gcr.io/cloud-builders/gsutil
    entrypoint: "bash"
    env:
    - COMMIT_SHA=$COMMIT_SHA
    - BRANCH_NAME=$BRANCH_NAME
    args:
    - "-c"
    - |
      set -euxo pipefail

      gsutil -m rsync -d -r api-docs gs://oscoin-apidocs/${COMMIT_SHA}
images:
- "eu.gcr.io/$PROJECT_ID/oscoin"
- "eu.gcr.io/$PROJECT_ID/oscoin-cli"
- "eu.gcr.io/$PROJECT_ID/haskell-scratch:integer-gmp"
