timeout: 7200s # Cache misses are slow to rebuild
options:
  machineType: N1_HIGHCPU_8
steps:
  - id: "Format (shell scripts)"
    waitFor: ["-"]
    name: gcr.io/cloud-builders/curl
    entrypoint: "bash"
    args: ["./scripts/check-shell-format.sh"]

  - id: "Lint (shellcheck)"
    waitFor: ["-"]
    name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args: ["./scripts/shellcheck.sh"]

  - id: "Load cache"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: "bash"
    env:
    - BRANCH_NAME=$BRANCH_NAME
    args:
    - "-c"
    - |
      source scripts/ci-cache.sh
      load-cache

  - id: "Build deps"
    name: "haskell:8.6.3"
    env:
    - STACK_ROOT=/workspace/.stack
    entrypoint: "bash"
    args:
    - "-c"
    - |
      set -euxo pipefail

      rm -rfv /workspace/.stack/global-project

      stack config set system-ghc  --global true
      stack config set install-ghc --global false

      stack build --no-terminal stylish-haskell hlint weeder
      stack build --no-terminal --test --dependencies-only

  - id: "Save cache"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: "bash"
    env:
    - BRANCH_NAME=$BRANCH_NAME
    args:
    - "-c"
    - |
      source scripts/ci-cache.sh
      save-cache

  - id: "Format (haskell)"
    waitFor:
    - Save cache
    name: "haskell:8.6.3"
    env:
    - STACK_ROOT=/workspace/.stack
    args:
    - ./scripts/check-haskell-format.sh

  - id: "Lint (hlint)"
    waitFor:
    - Save cache
    name: "haskell:8.6.3"
    env:
    - STACK_ROOT=/workspace/.stack
    args: ["stack", "exec", "--", "hlint", "."]

  - id: "Test & Build"
    waitFor:
    - Save cache
    name: "haskell:8.6.3"
    entrypoint: "bash"
    env:
    - STACK_ROOT=/workspace/.stack
    - BRANCH_NAME=$BRANCH_NAME
    args:
    - "-c"
    - |
      set -euo pipefail

      if [ "$BRANCH_NAME" == "master" ]; then
        stack build \
          --test \
          --flag=oscoin:static \
          --no-terminal \
          --pedantic \
          --copy-bins \
          --local-bin-path=/workspace/bin \
          --haddock \
          --exec="mv $(stack path --local-doc-root) api-docs"
      else
        stack build --test --no-terminal --pedantic
      fi

  - id: "Lint (weeder)"
    waitFor:
    - Test & Build
    name: "haskell:8.6.3"
    env:
    - STACK_ROOT=/workspace/.stack # weeder uses stack under the hood
    args: ["stack", "exec", "--", "weeder", "."]

  - id: "Publish images"
    waitFor:
    - Lint (weeder)
    name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    env:
    - PROJECT_ID=$PROJECT_ID
    - COMMIT_SHA=$COMMIT_SHA
    - BRANCH_NAME=$BRANCH_NAME
    args:
    - "-c"
    - |
      set -euo pipefail

      if [ "$BRANCH_NAME" == "master" ]; then
        bins=(
          /workspace/bin/oscoin
          /workspace/bin/oscoin-cli
        )

        echo "$${bins[*]}" | xargs -P8 -n1 ./scripts/publish-image.sh
      fi

  - id: "Publish Haddocks"
    waitFor:
    - Lint (weeder)
    name: gcr.io/cloud-builders/gsutil
    entrypoint: "bash"
    env:
    - COMMIT_SHA=$COMMIT_SHA
    - BRANCH_NAME=$BRANCH_NAME
    args:
    - "-c"
    - |
      set -euxo pipefail

      if [ "$BRANCH_NAME" == "master" ]; then
        gsutil -m rsync -d -r api-docs gs://oscoin-apidocs/${COMMIT_SHA}
      fi
