name: oscoin
version: '0.1.0.0'
synopsis: open-source collaboration network
author: Monadic
maintainer: team@monadic.xyz
copyright: 2018 Monadic
license: BSD4
github: oscoin/oscoin

dependencies:
  - base >=4.11.1.0 && <5

data-files:
  - data/blockstore.sql
  - data/genesis.yaml

flags:
    static:
        description: Statically link executables
        manual: true
        default: false

library:
  source-dirs: src
  dependencies:
    - Spock
    - aeson
    - async
    - avl-auth
    - binary
    - bytestring
    - cacophony >= 0.10.1
    - comonad
    - cborg
    - clock
    - conduit
    - conduit-extra
    - containers
    - cryptonite
    - deepseq
    - directory
    - direct-sqlite
    - dlist
    - dns
    - ekg
    - ekg-core
    - fast-logger
    - filepath
    - formatting
    - generics-sop
    - gossip
    - hashable
    - hostname
    - http-api-data
    - http-client
    - http-types
    - iproute
    - memory
    - microlens
    - microlens-mtl
    - mmorph
    - mtl
    - multibase
    - multihash-cryptonite
    - multihash-serialise
    - network
    - optparse-applicative
    - prettyprinter
    - pretty-terminal
    - profunctors
    - protolude
    - random
    - retry
    - safe-exceptions
    - semigroups
    - serialise
    - splitmix
    - sqlite-simple
    - stm >=2.4.5.0
    - text
    - transformers
    - vector
    - wai
    - wai-middleware-static
    - writer-cps-mtl
    - yaml

executables:
  oscoin:
    main: exe/node/Main.hs
    when:
    - condition: "flag(static)"
      ld-options: -static
    dependencies:
      - async
      - containers
      - http-types
      - managed
      - optparse-applicative
      - oscoin
      - semigroups
      - wai
      - warp
      - yaml
    ghc-options:
      - -with-rtsopts=-T
      - -threaded

  oscoin-cli:
    main: exe/cli/Main.hs
    when:
    - condition: "flag(static)"
      ld-options: -static
    dependencies:
      - oscoin

tests:
  documentation:
    main: telemetry.lhs
    source-dirs: docs
    ghc-options: -pgmL markdown-unlit
    dependencies:
      - oscoin
      - markdown-unlit
      - wai

  test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O
    dependencies:
      - Diff
      - QuickCheck
      - aeson
      - async
      - avl-auth
      - binary
      - bytestring
      - cacophony
      - cborg
      - conduit
      - containers
      - cryptonite
      - directory
      - dns
      - filepath
      - formatting
      - hashable
      - hedgehog
      - hedgehog-quickcheck
      - http-api-data
      - http-client
      - http-types
      - iproute
      - memory
      - microlens
      - microlens-mtl
      - mtl
      - multibase
      - network
      - nicify-lib
      - optparse-applicative
      - oscoin
      - quickcheck-instances
      - process
      - random
      - random-shuffle
      - retry
      - safe-exceptions
      - serialise
      - sqlite-simple
      - splitmix
      - stm-conduit
      - streaming-commons
      - tasty >=1.0.0.1
      - tasty-fail-fast
      - tasty-hedgehog
      - tasty-hunit >=0.10.0.1
      - tasty-quickcheck
      - temporary
      - text
      - transformers
      - wai
      - wai-extra

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - ParallelListComp
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - TupleSections
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -fno-print-expanded-synonyms
  - -funbox-small-strict-fields
