name: oscoin
version: '0.1.0.0'
synopsis: open-source collaboration network
author: Monadic
maintainer: team@monadic.xyz
copyright: 2018 Monadic
license: BSD4
github: oscoin/oscoin

dependencies:
  - base >=4.11.1.0 && <4.12

data-files:
  - data/rad/prelude.rad
  - data/genesis.yaml

flags:
    static:
        description: Statically link executables
        manual: true
        default: false

library:
  source-dirs: src
  dependencies:
    - Spock
    - aeson
    - ansi-terminal
    - async
    - avl-auth
    - base16-bytestring
    - base58-bytestring
    - base64-bytestring
    - binary
    - bytestring
    - cacophony >= 0.10.1
    - cborg
    - clock
    - conduit
    - containers
    - cryptonite
    - data-default
    - deepseq
    - directory
    - direct-sqlite
    - dlist
    - fast-logger
    - filepath
    - focus
    - formatting
    - gossip
    - hashable
    - http-api-data
    - http-client
    - http-media
    - http-types
    - memory
    - microlens
    - microlens-mtl
    - mmorph
    - mtl
    - network
    - optparse-applicative
    - prettyprinter
    - protolude
    - radicle
    - random
    - safe-exceptions
    - semigroups
    - serialise
    - sqlite-simple
    - stm >=2.4.5.0
    - stm-containers
    - tagged
    - text
    - transformers
    - typed-process
    - wai
    - wai-extra
    - wai-middleware-static
    - writer-cps-mtl
    - yaml

executables:
  oscoin:
    main: exe/node/Main.hs
    when:
    - condition: "flag(static)"
      ld-options: -static
    dependencies:
      - async
      - network
      - optparse-applicative
      - oscoin
      - semigroups
      - yaml

  oscoin-cli:
    main: exe/cli/Main.hs
    when:
    - condition: "flag(static)"
      ld-options: -static
    dependencies:
      - oscoin

  git-remote-oss:
    main: exe/git-remote-helper/Main.hs
    when:
    - condition: "flag(static)"
      ld-options: -static
    dependencies:
      - oscoin
      - semigroups

tests:
  test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O
    dependencies:
      - Diff
      - QuickCheck
      - aeson
      - async
      - binary
      - bytestring
      - cacophony
      - conduit
      - containers
      - cryptonite
      - data-default
      - directory
      - filepath
      - formatting
      - hashable
      - hedgehog
      - http-api-data
      - http-media
      - http-types
      - memory
      - microlens
      - mtl
      - network
      - nicify-lib
      - optparse-applicative
      - oscoin
      - quickcheck-instances
      - radicle
      - random
      - random-shuffle
      - safe-exceptions
      - scientific
      - serialise
      - stm-conduit
      - streaming-commons
      - tasty >=1.0.0.1
      - tasty-hedgehog
      - tasty-hunit >=0.10.0.1
      - tasty-quickcheck
      - temporary
      - text
      - transformers
      - wai
      - wai-extra

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - ParallelListComp
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - TupleSections
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -fno-print-expanded-synonyms
  - -funbox-small-strict-fields
