name: oscoin
version: '0.1.0.0'
synopsis: open-source collaboration network
author: Monadic
maintainer: team@monadic.xyz
copyright: 2018 Monadic
license: BSD4
github: oscoin/oscoin

dependencies:
  - base >=4.11.1.0 && <4.12
  - aeson
  - async
  - base16-bytestring
  - base58-bytestring
  - base64-bytestring
  - binary
  - bytestring
  - containers
  - cryptonite
  - data-default
  - data-has
  - dlist
  - fast-logger
  - formatting
  - hashable
  - http-api-data
  - http-client
  - http-types
  - iproute
  - memory
  - merkle-tree
  - microlens
  - mtl
  - network
  - network-multicast
  - optparse-applicative
  - primitive
  - prettyprinter
  - radicle
  - random
  - random-shuffle
  - recursion-schemes
  - safe-exceptions
  - scientific
  - serialise
  - semigroups
  - splitmix
  - Spock
  - stm >=2.4.5.0
  - text
  - time
  - transformers
  - unordered-containers
  - wai
  - wai-extra
  - wai-middleware-static
  - writer-cps-mtl
  - yaml

data-files:
  - node/rad/prelude.rad

library:
  source-dirs: src

executables:
  oscoin:
    main: node/Main.hs
    dependencies:
      - iproute
      - optparse-generic >= 1.3.0
      - oscoin
  oscoin-cli:
    main: cli/Main.hs
    dependencies:
      - oscoin
  txgen:
    main: txgen/Main.hs
    dependencies:
      - optparse-generic >= 1.3.0
      - oscoin

tests:
  test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O
    dependencies:
      - algebraic-graphs
      - hedgehog
      - microlens
      - microlens-aeson
      - oscoin
      - QuickCheck
      - quickcheck-instances
      - tasty >=1.0.0.1
      - tasty-hedgehog
      - tasty-hunit >=0.10.0.1
      - tasty-quickcheck
      - tasty-expected-failure
      - vector

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - ParallelListComp
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -fno-print-expanded-synonyms
  - -funbox-small-strict-fields
