resolver: lts-12.14

packages:
- .

extra-deps:
- algebraic-graphs-0.1.1.1
- base58-bytestring-0.1.0
- cborg-0.2.1.0
- half-0.3
- merkle-tree-0.1.0
- reroute-0.5.0.0
- serialise-0.2.1.0
- Spock-0.13.0.0
- Spock-core-0.13.0.0

- git: http://git.oscoin.io/radicle
  commit: 12707c83663909d303e4daf1806f22a779be7598

# Due to version bounds
# https://github.com/centromere/cacophony/pull/10
- git: https://github.com/kim/cacophony
  commit: 5afdce755eb4942167f1beed927e0890a481efe5

ghc-options:
  "$locals": -fhide-source-paths
