resolver: lts-11.5

packages:
- .

extra-deps:
- acid-state-0.14.3
- kademlia-1.1.0.0
- merkle-tree-0.1.0
- base58-bytestring-0.1.0
- monad-stm-0.1.0.2
- git: git@github.com:cloudhead/wai
  commit: a3464cc76198d51ae7cf838690eadeeefd627f9c
  subdirs:
    - wai-extra

ghc-options:
  "$locals": -fhide-source-paths
