resolver: lts-12.0

packages:
- .

extra-deps:
- algebraic-graphs-0.1.1.1
- merkle-tree-0.1.0
- base58-bytestring-0.1.0
- Spock-0.13.0.0
- Spock-core-0.13.0.0
- reroute-0.5.0.0
- serialise-0.2.0.0
- cborg-0.2.0.0
- half-0.2.2.3

- git: git@github.com:cloudhead/wai
  commit: a3464cc76198d51ae7cf838690eadeeefd627f9c
  subdirs:
    - wai-extra

- git: http://git.oscoin.io/radicle
  commit: 2b9ddab4963bf04f0148ff0974acdb5ebab5834f

ghc-options:
  "$locals": -fhide-source-paths
