resolver: lts-12.0

packages:
- .

extra-deps:
- algebraic-graphs-0.1.1.1
- cborg-0.2.0.0
- merkle-tree-0.1.0
- reroute-0.5.0.0
- Spock-0.13.0.0
- Spock-core-0.13.0.0
- serialise-0.2.0.0
- half-0.2.2.3

- git: http://git.oscoin.io/radicle
  commit: 3eb11aa4080a9f052e46641cbc4126a298538d73

ghc-options:
  "$locals": -fhide-source-paths
