resolver: lts-12.17

packages:
- .

extra-deps:
- algebraic-graphs-0.1.1.1
- base58-bytestring-0.1.0
- cacophony-0.10.1
- cborg-0.2.1.0
- half-0.3
- reroute-0.5.0.0
- serialise-0.2.1.0
- Spock-0.13.0.0
- Spock-core-0.13.0.0
- formatting-6.3.7 # Handy to have a Buildable [a] instance
- pretty-terminal-0.1.0.0

- git: http://git.oscoin.io/radicle
  commit: 12707c83663909d303e4daf1806f22a779be7598

- git: https://github.com/oscoin/avl-auth
  commit: 2508d2c44b87354f6c1e4fda619b43f2f0705c77

- git: https://github.com/oscoin/gossip
  commit: 3307ec12e30288c21ef20030be871ba3e518b58b

ghc-options:
  "$locals": -fhide-source-paths
