version: 2
jobs:
    build:
        docker:
          - image: haskell:8.4.3
        steps:
            - checkout
            - restore_cache:
                keys:
                  - stack-work-v3-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
                  # If an exact match is unavailable, use the most recent one
                  - stack-work-v3-
                paths:
                    - ~/.stack
            - run: stack install hlint stylish-haskell
            - run:
                name: Formatting
                command: ./.circleci/check-fmt.sh
            - run:
                name: Lint
                command: git ls-files | grep '\.l\?hs$' | xargs stack exec -- hlint "$@"
            - run:
                name: Build
                command: stack build --no-terminal --pedantic --test --no-run-tests
            - run:
                name: Test
                command: stack test --no-terminal
            - run:
                name: Clean cache
                # These files are large (~600MB) and are not needed
                command: rm ~/.stack/indices/Hackage/00-index.tar* || true
            - save_cache:
                key: stack-work-v3-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
                paths:
                    - ~/.stack
