{
 "title": "Oscoin",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Blocks Mined (5m rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oscoin_blocks_mined_total[5m])"
    }
   ]
  },
  {
   "title": "Blocks Applied (5m rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oscoin_blocks_applied_total[5m])"
    }
   ]
  },
  {
   "title": "Blocks Sent (5min rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oscoin_blocks_sent_total[5m])"
    }
   ]
  },
  {
   "title": "Blocks Received (5min rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oscoin_blocks_received_total[5m])"
    }
   ]
  },
  {
   "title": "Consensus Difficulty Adjustments (5min rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oscoin_consensus_difficulty_adjustments_total[5m])"
    }
   ]
  },
  {
   "title": "Blocks Stale (5m rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oscoin_blocks_stale_total[5m])"
    }
   ]
  },
  {
   "title": "HTTP Requests (5min rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oscoin_api_http_requests_total[5m])"
    }
   ]
  }
 ]
}