{
 "title": "P2P",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Protocol / Payload Messages 5min rate (+ egress / - ingress)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(oscoin_p2p_gossip_protocol_sent_total[5m])) ",
     "legendFormat": "Protocol Egress"
    },
    {
     "expr": "- sum (rate(oscoin_p2p_gossip_protocol_received_total[5m]))",
     "legendFormat": "Protocol Ingress"
    },
    {
     "expr": "- sum(rate(oscoin_p2p_gossip_protocol_received_payload_total[5m]))",
     "legendFormat": "Payload Ingress"
    },
    {
     "expr": "sum (rate(oscoin_p2p_gossip_protocol_sent_payload_total[5m])  )",
     "legendFormat": "Payload Egress"
    }
   ]
  },
  {
   "title": "Disconnects 5min rate (+ initiated, - by peer)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "- sum(rate(oscoin_p2p_gossip_connection_reset_by_peer_total[5m]))"
    },
    {
     "expr": "sum(rate(oscoin_p2p_gossip_connection_disconnected_total[5m]))"
    }
   ]
  },
  {
   "title": "Handshake 5min rate (+ completions, - errors)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oscoin_p2p_handshake_completions_total[5m]))"
    },
    {
     "expr": "-sum(rate(oscoin_p2p_handshake_errors_total[5m]))"
    }
   ]
  },
  {
   "title": "Connects 5min rate (+ success, - error)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oscoin_p2p_gossip_connection_connect_success_total[5m]))"
    },
    {
     "expr": "-sum(rate(oscoin_p2p_gossip_connection_connect_errors_total[5m]))"
    }
   ]
  },
  {
   "title": "Protocol Errors (5min rate)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oscoin_p2p_gossip_protocol_errors_total[5m])"
    }
   ]
  },
  {
   "title": "Network Partitions (5min rate)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oscoin_p2p_network_partitions_total[5m])"
    }
   ]
  },
  {
   "title": "Connections Accepted (5min rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oscoin_p2p_gossip_connection_accepted_total[5m])"
    }
   ]
  },
  {
   "title": "Discovery 5min rate (+ attempts, - successes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oscoin_disco_discos_attempts_total[5m])"
    },
    {
     "expr": "-rate(oscoin_disco_discos_successes_total[5m])"
    }
   ]
  }
 ]
}