{
 "title": "RTS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Num GCs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(rts_gc_num_gcs[5m])" }
   ]
  },
  {
   "title": "Bytes Allocated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "rts_gc_bytes_allocated" }
   ]
  },
  {
   "title": "Bytes Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(rts_gc_cumulative_bytes_used[5m])"
    }
   ]
  },
  {
   "title": "GC Wall",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(rts_gc_gc_wall_ms[5m])" }
   ]
  }
 ]
}